c9_container:
    image: sapk/cloud9
    container_name: pinterest_c9
    #TODO: name by variable using ${pwd}
    ports:
        - "8181:8181"
        - "8888:8080"
        # the second port is for exposing container port for running service
    volumes:
        - ${pwd}:/workspace
    command: --auth "admin:admin"
